name: Release

# FIXME: This workflow still missing release step 
on: workflow_dispatch:
  # push:
  #   branches: [main]

jobs:
  release-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and release
        uses: wangyoucao577/go-release-action@v1.22
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: 1.17
          goos: linux
          goarch: amd64
          overwrite: true
#    - name: Test
#      run: go test -v ./...
